// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCceSl2yHS8HU7UpQ1Bf8COdsR_cMiHqY',
    appId: '1:676299210480:web:9737032e6fe40fcf32cc35',
    messagingSenderId: '676299210480',
    projectId: 'news-sanbercode',
    authDomain: 'news-sanbercode.firebaseapp.com',
    storageBucket: 'news-sanbercode.firebasestorage.app',
    measurementId: 'G-NFHDY6640P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVj2Zud2-d5R0EbOs8HYA2hywy-e90zY',
    appId: '1:676299210480:android:0c176a8dd3a5c33932cc35',
    messagingSenderId: '676299210480',
    projectId: 'news-sanbercode',
    storageBucket: 'news-sanbercode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfjDHmcSy9u6nQLzJV6p3awPxBiuO6pEw',
    appId: '1:676299210480:ios:31c9e6a1eb5cde4832cc35',
    messagingSenderId: '676299210480',
    projectId: 'news-sanbercode',
    storageBucket: 'news-sanbercode.firebasestorage.app',
    iosBundleId: 'com.example.coreComponent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfjDHmcSy9u6nQLzJV6p3awPxBiuO6pEw',
    appId: '1:676299210480:ios:31c9e6a1eb5cde4832cc35',
    messagingSenderId: '676299210480',
    projectId: 'news-sanbercode',
    storageBucket: 'news-sanbercode.firebasestorage.app',
    iosBundleId: 'com.example.coreComponent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCceSl2yHS8HU7UpQ1Bf8COdsR_cMiHqY',
    appId: '1:676299210480:web:a640629463ea725a32cc35',
    messagingSenderId: '676299210480',
    projectId: 'news-sanbercode',
    authDomain: 'news-sanbercode.firebaseapp.com',
    storageBucket: 'news-sanbercode.firebasestorage.app',
    measurementId: 'G-M5Z45QVNFM',
  );
}
